language: python
sudo: false
python: 2.7
env:
    matrix:
        - TOX_ENV=py27-django110
        - TOX_ENV=py27-django111
        - TOX_ENV=py27-flake8
install:
    - pip install tox-travis
script:
    - tox -e $TOX_ENV
