# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-27 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0003_project_archive_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='name',
            field=models.SlugField(help_text='Assign a name for the metadata field (letters, numbers, underscores, and hyphens are permissible).'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='value_sets',
            field=models.ManyToManyField(blank=True, help_text='In addition to values manually assigned, values in selected pre-defined sets will also be available to metadata fields.', to='nomination.ValueSet', verbose_name='metadata value sets'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='values',
            field=models.ManyToManyField(blank=True, help_text='Allowed value for metadata field.', through='nomination.Metadata_Values', to='nomination.Value', verbose_name='values'),
        ),
        migrations.AlterField(
            model_name='metadata_values',
            name='value_order',
            field=models.PositiveIntegerField(default=1, help_text='Change the ordering of the value fields, ordered lowest to highest'),
        ),
        migrations.AlterField(
            model_name='nominator',
            name='nominator_email',
            field=models.CharField(help_text='An email address for identifying your nominations in the system.', max_length=100),
        ),
        migrations.AlterField(
            model_name='nominator',
            name='nominator_institution',
            field=models.CharField(help_text='Your institutional affiliation.', max_length=100),
        ),
        migrations.AlterField(
            model_name='nominator',
            name='nominator_name',
            field=models.CharField(help_text='Your name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='admin_email',
            field=models.CharField(help_text='Email address of project administrator.', max_length=80),
        ),
        migrations.AlterField(
            model_name='project',
            name='admin_name',
            field=models.CharField(help_text='Name of project administrator.', max_length=80),
        ),
        migrations.AlterField(
            model_name='project',
            name='archive_url',
            field=models.URLField(blank=True, help_text='Base URL for accessing site archives.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='nomination_end',
            field=models.DateTimeField(help_text='Date to stop accepting URL nominations.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='nomination_start',
            field=models.DateTimeField(help_text='Date to start accepting URL nominations.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(help_text='Description of project.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end',
            field=models.DateTimeField(help_text='Ending date for project.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(help_text='Name given to nomination project.', max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_slug',
            field=models.CharField(help_text='Up to 25 character identifier for the project (used in URLS, etc.).', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_start',
            field=models.DateTimeField(help_text='Starting date for project.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.CharField(help_text='Project affiliated URL.', max_length=255),
        ),
        migrations.AlterField(
            model_name='project_metadata',
            name='description',
            field=models.CharField(help_text='Used as a descriptive title for the metadata field on Web forms.', max_length=255),
        ),
        migrations.AlterField(
            model_name='project_metadata',
            name='form_type',
            field=models.CharField(choices=[('checkbox', 'checkbox'), ('date', 'date'), ('radio', 'radio button'), ('select', 'menu-select multiple values'), ('selectsingle', 'menu-select single value'), ('text', 'text input'), ('textarea', 'text area')], help_text='Type of HTML form element that should represent the field.', max_length=30),
        ),
        migrations.AlterField(
            model_name='project_metadata',
            name='help',
            field=models.CharField(blank=True, help_text='String used on Web forms to prompt users for accurate data.', max_length=255),
        ),
        migrations.AlterField(
            model_name='project_metadata',
            name='metadata_order',
            field=models.PositiveIntegerField(default=1, help_text='Change the ordering of the metadata fields, ordered lowest to highest'),
        ),
        migrations.AlterField(
            model_name='project_metadata',
            name='required',
            field=models.BooleanField(help_text='Are users required to submit data for this field when nominating a URL?'),
        ),
        migrations.AlterField(
            model_name='url',
            name='attribute',
            field=models.CharField(help_text='A property of the URL you wish to describe.', max_length=255),
        ),
        migrations.AlterField(
            model_name='url',
            name='entity',
            field=models.CharField(help_text='The URL to nominate for capture.', max_length=300),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_project',
            field=models.ForeignKey(help_text='The project for which you want to add a URL.', on_delete=django.db.models.deletion.CASCADE, to='nomination.Project'),
        ),
        migrations.AlterField(
            model_name='url',
            name='value',
            field=models.CharField(help_text='The value of the associated attribute.', max_length=255),
        ),
        migrations.AlterField(
            model_name='value',
            name='key',
            field=models.CharField(help_text='Up to 35 character identifier for the metadata field.', max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.CharField(help_text='Permitted value for associated metadata field.', max_length=255),
        ),
        migrations.AlterField(
            model_name='valueset',
            name='name',
            field=models.CharField(help_text='Name given to value set.', max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='valueset',
            name='values',
            field=models.ManyToManyField(through='nomination.Valueset_Values', to='nomination.Value', verbose_name='values'),
        ),
        migrations.AlterField(
            model_name='valueset_values',
            name='value_order',
            field=models.PositiveIntegerField(default=1, help_text='Change the ordering of the value fields, ordered lowest to highest'),
        ),
    ]
