# Generated by Django 4.1.3 on 2024-09-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomination', '0005_auto_20210429_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='value',
            field=models.CharField(help_text='The value of the associated attribute.', max_length=305),
        ),
    ]
